In [4]:
import torch
import torch.nn as nn
import math

### Embeddings

In [106]:
vocabulary = {
    "your":     0,
    "cat":      1,
    "is":       2,
    "a":        3,
    "lovely":   4,
    "my":       5,
    "you":      6,
    "olle":     7,
    "matrea":   8,
    "dad":         9,
    "mom":         10,
    "pet":         11,
    "rosie":         12,
    "fumble":        13,
    "petrol":         14,
    "tummy":         15,
    "sage":         16,
    "duck":         17,
    "liver":         18,
    "onion":         19,
    "tomato":         20,
    "pepper":         21,
    "langchain":         22,
    "are":         23,
    "the":         24,
    "best":         25,
    "of":         26,
    "all":         27,
    "bum":         28,
    "lol":         29,
    "cool":         30,
    "story":         31,
    "man":         32,
    "woman":         33,
    "[UNK]":    34  # Unknown token for words not in the vocabulary
}

In [107]:
sentence = ["Your", "cat", "is", "a", "lovely", "cat", "mate"]

In [113]:
vocabulary.get(sentence[6].lower(), vocabulary["[UNK]"])

34

In [108]:
# Convert to lowercase to match the vocabulary keys
indices = [vocabulary.get(word.lower(), vocabulary["[UNK]"]) for word in sentence]
indices

[0, 1, 2, 3, 4, 1, 34]

In [114]:
input_indices = torch.tensor(indices, dtype=torch.long)
input_indices

tensor([ 0,  1,  2,  3,  4,  1, 34])

In [115]:
class InputEmbeddings(nn.Module):

    def __init__(self, d_model: int, vocab_size: int):
        super().__init__()
        self.d_model = d_model # input dimensionality
        self.vocab_size = vocab_size # the total number of different words that are in the model's vocabulary
        self.embedding = nn.Embedding(vocab_size, d_model)
        # ^size of the dict of embeddings + embedding vector

    def forward(self, input):
        return self.embedding(input) * math.sqrt(self.d_model)

In [125]:
d_model =  8 # dims of embeddings
vocab_size = len(vocabulary)
vocab_size

35

In [122]:
input_embedding = InputEmbeddings(d_model, vocab_size)

In [130]:
input

tensor([30, 20, 10])

In [131]:
output = input_embedding(input_indices)
output

tensor([[-2.9320,  0.2359, -0.1124,  6.3901, -1.9721,  5.6444, -3.2587,  4.3600],
        [-2.6714, -0.8874,  4.7699, -1.6078,  0.0722,  0.8359, -0.2876, -2.8380],
        [-5.4204, -1.2565, -3.0293,  5.3176,  1.3457,  5.7312, -1.9031,  4.4588],
        [ 7.1102, -1.0455,  1.9530, -0.1062, -0.9734,  5.6528, -0.9597,  2.4300],
        [-1.2621, -1.3150,  2.5110, -2.3639, -0.7236,  2.3629, -0.4232, -0.8170],
        [-2.6714, -0.8874,  4.7699, -1.6078,  0.0722,  0.8359, -0.2876, -2.8380],
        [ 2.4668, -1.3098,  0.6046, -2.8471,  1.0624, -4.8806,  1.7584,  1.4341]],
       grad_fn=<MulBackward0>)

In [129]:
len(output[0])

8

In [127]:
len(input_indices)

7

### Positional Encoding

In [ ]:
class PositionalEncoding(nn.Module):
    