In [4]:
import torch
from torch import nn

In [39]:
# 4 previous Mondays of electric fan packages sold + if it was above 30 degrees during that day
input_data = torch.Tensor([
    # [100, 1000, 200], [0, 1, 0],
    [100, 1000, 200, 100], [0, 1, 0, 0],
    # [[100, 1000, 200, 100], [0, 1, 0, 0]],
    # [[100, 1000, 200, 100], [0, 1, 0, 0]],
    # [[100, 1000, 200, 100], [0, 1, 0, 0]],
                           ],
                          )
input_data

tensor([[ 100., 1000.,  200.,  100.],
        [   0.,    1.,    0.,    0.]])

In [40]:
layer_1 = nn.Linear(in_features = 4,
                    out_features= 4, # 4 neurons aka the dots in the visualisations
                    bias=True) # a bias for each neuron
layer_1

Linear(in_features=4, out_features=4, bias=True)

In [41]:
layer_2 = nn.Linear(in_features = 4,
                    out_features= 1, # 1 neuron
                    bias=True) # a bias for each neuron
layer_2

Linear(in_features=4, out_features=1, bias=True)

In [42]:
layer_1.weight

Parameter containing:
tensor([[-0.2991, -0.1143,  0.1905, -0.2558],
        [ 0.0403,  0.3230, -0.2433, -0.4987],
        [-0.1398,  0.0134, -0.0604, -0.2039],
        [ 0.1467, -0.4083, -0.3024,  0.4943]], requires_grad=True)

In [45]:
layer_1.bias

Parameter containing:
tensor([ 0.2040, -0.2480, -0.2273, -0.3506], requires_grad=True)

In [43]:
layer_2.weight

Parameter containing:
tensor([[0.4571, 0.3833, 0.4641, 0.4611]], requires_grad=True)

In [46]:
layer_2.bias

Parameter containing:
tensor([-0.1421], requires_grad=True)

In [48]:
layer_1(input_data)

tensor([[-1.3146e+02,  2.2827e+02, -3.3239e+01, -4.0503e+02],
        [ 8.9733e-02,  7.5042e-02, -2.1388e-01, -7.5893e-01]],
       grad_fn=<AddmmBackward0>)

In [44]:
layer_2(layer_1(input_data))

tensor([[-174.9507],
        [  -0.5215]], grad_fn=<AddmmBackward0>)

the calculation in the end is to take:

the input feature * the current weight of that layer (that gets updated during training) and add a bias term, that also gets updated during training.

``` feature * weight + bias ```

In [49]:
# output of layer 1 = input * w + b
100*(-0.2991) + 0.2040

-29.705999999999996

In [47]:
# output of layer 2 = input*w1*w2 + b1*w2 + b2
100*-0.2991*0.4571 + 0.2040*0.4571 + (-0.1421)

-13.720712599999997

Note: it will have one weight per input feature.

__________

Going from one linear layer to the other with no activation function -> that means it simply learns linear relationships between the layers. And one of the main points of NNs is to be able to learn non-linear relationships between datapoints. 