In [1]:
import torch
import torch.nn as nn

In [2]:
data = torch.tensor([1,2,3,4])
data

tensor([1, 2, 3, 4])

In [31]:
another_one = torch.tensor([[10,20,30,50,60],[1,2,3,5,6]])
another_one

tensor([[10, 20, 30, 50, 60],
        [ 1,  2,  3,  5,  6]])

In [14]:
data.shape[0]

4

In [20]:
another_one.shape

torch.Size([2, 5])

In [15]:
another_one.shape[0]

2

In [16]:
another_one.shape[1]

5

In [18]:
num_heads = 2

In [21]:
another_one = another_one.view(another_one.shape[1],another_one.shape[0])
another_one

tensor([[10, 20],
        [30, 50],
        [60,  1],
        [ 2,  3],
        [ 5,  6]])

In [37]:
another_one.transpose(-2,1)

tensor([[10,  1],
        [20,  2],
        [30,  3],
        [50,  5],
        [60,  6]])

In [38]:
Q, K, V = 1

TypeError: cannot unpack non-iterable int object

In [7]:
Q = K = V = 1

In [6]:
Q

NameError: name 'Q' is not defined

In [41]:
K

1

In [42]:
V

1

In [8]:
add = lambda Q, K, V: Q+K+V
add(Q,K,V)

3